// Copyright (c) 2026 Clément Metz - MIT License
// SPDX-License-Identifier: MIT
#pragma once

#include "constest_asserts.hpp"

#define CONSTEST_INTERNAL_EQ(a, b) ((a) == (b))
#define CONSTEST_INTERNAL_NE(a, b) ((a) != (b))
#define CONSTEST_INTERNAL_LT(a, b) ((a) < (b))
#define CONSTEST_INTERNAL_LE(a, b) ((a) <= (b))
#define CONSTEST_INTERNAL_GT(a, b) ((a) > (b))
#define CONSTEST_INTERNAL_GE(a, b) ((a) >= (b))
#define CONSTEST_INTERNAL_TRUE(a)  (static_cast<bool>(a))
#define CONSTEST_INTERNAL_FALSE(a) (!static_cast<bool>(a))

// EXPECT macros
#define CONSTEXPR_EXPECT_EQ(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_EQ(__VA_ARGS__), EXPECT_EQ(__VA_ARGS__), CONSTEST_INTERNAL_EQ(__VA_ARGS__))
#define CONSTEXPR_EXPECT_NE(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_NE(__VA_ARGS__), EXPECT_NE(__VA_ARGS__), CONSTEST_INTERNAL_NE(__VA_ARGS__))
#define CONSTEXPR_EXPECT_LT(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_LT(__VA_ARGS__), EXPECT_LT(__VA_ARGS__), CONSTEST_INTERNAL_LT(__VA_ARGS__))
#define CONSTEXPR_EXPECT_LE(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_LE(__VA_ARGS__), EXPECT_LE(__VA_ARGS__), CONSTEST_INTERNAL_LE(__VA_ARGS__))
#define CONSTEXPR_EXPECT_GT(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_GT(__VA_ARGS__), EXPECT_GT(__VA_ARGS__), CONSTEST_INTERNAL_GT(__VA_ARGS__))
#define CONSTEXPR_EXPECT_GE(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_GE(__VA_ARGS__), EXPECT_GE(__VA_ARGS__), CONSTEST_INTERNAL_GE(__VA_ARGS__))
#define CONSTEXPR_EXPECT_TRUE(...)  CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_TRUE(__VA_ARGS__), EXPECT_TRUE(__VA_ARGS__), CONSTEST_INTERNAL_TRUE(__VA_ARGS__))
#define CONSTEXPR_EXPECT_FALSE(...) CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_FALSE(__VA_ARGS__), EXPECT_FALSE(__VA_ARGS__), CONSTEST_INTERNAL_FALSE(__VA_ARGS__))

// ASSERT macros
#define CONSTEXPR_ASSERT_EQ(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_EQ(__VA_ARGS__), ASSERT_EQ(__VA_ARGS__), CONSTEST_INTERNAL_EQ(__VA_ARGS__))
#define CONSTEXPR_ASSERT_NE(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_NE(__VA_ARGS__), ASSERT_NE(__VA_ARGS__), CONSTEST_INTERNAL_NE(__VA_ARGS__))
#define CONSTEXPR_ASSERT_LT(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_LT(__VA_ARGS__), ASSERT_LT(__VA_ARGS__), CONSTEST_INTERNAL_LT(__VA_ARGS__))
#define CONSTEXPR_ASSERT_LE(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_LE(__VA_ARGS__), ASSERT_LE(__VA_ARGS__), CONSTEST_INTERNAL_LE(__VA_ARGS__))
#define CONSTEXPR_ASSERT_GT(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_GT(__VA_ARGS__), ASSERT_GT(__VA_ARGS__), CONSTEST_INTERNAL_GT(__VA_ARGS__))
#define CONSTEXPR_ASSERT_GE(...)    CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_GE(__VA_ARGS__), ASSERT_GE(__VA_ARGS__), CONSTEST_INTERNAL_GE(__VA_ARGS__))
#define CONSTEXPR_ASSERT_TRUE(...)  CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_TRUE(__VA_ARGS__), ASSERT_TRUE(__VA_ARGS__), CONSTEST_INTERNAL_TRUE(__VA_ARGS__))
#define CONSTEXPR_ASSERT_FALSE(...) CONSTEST_INTERNAL_ASSERT_IMPL(CONSTEST_INTERNAL_FALSE(__VA_ARGS__), ASSERT_FALSE(__VA_ARGS__), CONSTEST_INTERNAL_FALSE(__VA_ARGS__))

#define CONSTEXPR_SECTION(...)       CONSTEST_INTERNAL_CONSTEXPR_SECTION_IMPL
#define CONSTEXPR_SECTION_DEBUG(...) CONSTEST_INTERNAL_CONSTEXPR_SECTION_DEBUG_IMPL