// Copyright (c) 2026 Clément Metz - MIT License
// SPDX-License-Identifier: MIT
#pragma once

#include "constest_asserts.hpp"
#include "constexpr_section.hpp"

#define CONSTEXPR_BOOST_TEST(expr) CONSTEST_INTERNAL_ASSERT(expr, BOOST_TEST(expr))

#define CONSTEXPR_SECTION(...) BOOST_TEST_CONTEXT(CONSTEST_INTERNAL_PASSED_AT_COMPILE_TIME __VA_ARGS__) CONSTEST_INTERNAL_CONSTEXPR_SECTION_IMPL

#define CONSTEXPR_SECTION_DEBUG(...) BOOST_TEST_CONTEXT(CONSTEST_INTERNAL_WARNING_DEBUGGING __VA_ARGS__) CONSTEST_INTERNAL_CONSTEXPR_SECTION_DEBUG_IMPL
