// Copyright (c) 2026 Clément Metz - MIT License
// SPDX-License-Identifier: MIT
#pragma once

#include "constest_asserts.hpp"
#include "constexpr_section.hpp"

#define CONSTEXPR_REQUIRE(...)       CONSTEST_INTERNAL_ASSERT(__VA_ARGS__, REQUIRE(__VA_ARGS__))
#define CONSTEXPR_REQUIRE_FALSE(...) CONSTEST_INTERNAL_ASSERT_NOT(__VA_ARGS__, REQUIRE_FALSE(__VA_ARGS__))
#define CONSTEXPR_CHECK(...)         CONSTEST_INTERNAL_ASSERT(__VA_ARGS__, CHECK(__VA_ARGS__))
#define CONSTEXPR_CHECK_FALSE(...)   CONSTEST_INTERNAL_ASSERT_NOT(__VA_ARGS__, CHECK_FALSE(__VA_ARGS__))

#define CONSTEXPR_SECTION(...)       SUBCASE(CONSTEST_INTERNAL_PASSED_AT_COMPILE_TIME __VA_ARGS__) CONSTEST_INTERNAL_CONSTEXPR_SECTION_IMPL
#define CONSTEXPR_SECTION_DEBUG(...) SUBCASE(CONSTEST_INTERNAL_WARNING_DEBUGGING __VA_ARGS__) CONSTEST_INTERNAL_CONSTEXPR_SECTION_DEBUG_IMPL